<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gmail</name>
   <tag></tag>
   <elementGuidId>ec61852b-ce6b-44e0-a8e8-96c44533b7d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gb_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='gb']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gmail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db8defb6-3867-41d7-bdd8-5a1d45532a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_6</value>
      <webElementGuid>814ff588-bea7-47a3-9891-2616f16fbd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gmail </value>
      <webElementGuid>c20012bd-763e-492f-8581-1df1b8192137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>e2f134a3-343d-40e9-aa8f-c06d7b6c20eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mail.google.com/mail/&amp;ogbl</value>
      <webElementGuid>d84e73b6-ecc3-4aad-900b-fc45ca2b9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>9af9c84b-8468-4e15-bfb1-c78742e7c13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gmail</value>
      <webElementGuid>abe19eb2-28f1-4550-916d-2e283beeef34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_R gb_8 gb_1f gb_8f&quot;]/div[@class=&quot;gb_7 gb_8&quot;]/a[@class=&quot;gb_6&quot;]</value>
      <webElementGuid>575c3470-073e-4642-b008-52d1f47915b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gb']/div/div/a</value>
      <webElementGuid>e35f3184-ef30-4e0c-917e-c54cac819b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gmail')]</value>
      <webElementGuid>aac84e03-501f-4390-8a50-8674dd94498d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[1]/following::a[1]</value>
      <webElementGuid>8ed95d93-3ae9-4df4-b5bd-846fcad9b3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::a[2]</value>
      <webElementGuid>445fbe28-bed3-467f-b108-0aea36e00ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/preceding::a[1]</value>
      <webElementGuid>1c3af99a-bf7c-488f-ba07-c34a6bea5c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[3]</value>
      <webElementGuid>073c6e55-d716-4dc6-8839-f8d542ca5ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gmail']/parent::*</value>
      <webElementGuid>645b52d7-eeb1-4697-a6a2-fa8c69275580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mail.google.com/mail/&amp;ogbl')]</value>
      <webElementGuid>a61a3917-9ed8-4764-91d8-5be6dc20d70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/a</value>
      <webElementGuid>9b1ba00d-5b8d-463b-a10a-7fda974825c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mail.google.com/mail/&amp;ogbl' and (text() = 'Gmail' or . = 'Gmail')]</value>
      <webElementGuid>b9ea300d-5287-4a47-b741-21095eacba5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
